import { firebaseConfig } from "./firebase-config.js";
import { initializeApp } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-app.js";
import { getAuth, createUserWithEmailAndPassword, signInWithEmailAndPassword, sendPasswordResetEmail, signOut, onAuthStateChanged, updateProfile } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-auth.js";
import { getFirestore, doc, setDoc, getDoc, addDoc, collection, query, orderBy, limit, getDocs, serverTimestamp } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js";

const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app),$=id=>document.getElementById(id);
const EX={Chest:["Chest Press","Incline Chest Press","Pec Deck","Hammer Strength MTS Chest Press"],Back:["Lat Pulldown","Seated Row","High Row"],Shoulders:["Shoulder Press","Lateral Raise","Rear Delt Fly"],Arms:["Biceps Curl","Triceps Pushdown","Dip Machine"],Legs:["Leg Press","Leg Extension","Seated Leg Curl"],Core:["Abdominal Crunch","Torso Rotation"],Cardio:["Treadmill","Stair Climber","Elliptical"]};
let user=null,workout=null,active=null,timer=null;

function msg(t,ok=false){$("authMessage").textContent=t;$("authMessage").className=ok?"message success":"message"}
function toast(t,type=""){const e=$("toast");e.textContent=t;e.className=`toast ${type}`;clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.add("hidden"),2500);e.classList.remove("hidden")}
function screen(name){["homeScreen","workoutScreen","historyScreen","profileScreen"].forEach(id=>$(id).classList.add("hidden"));$(`${name}Screen`).classList.remove("hidden");document.querySelectorAll(".navbtn").forEach(b=>b.classList.toggle("active",b.dataset.screen===name))}
document.querySelectorAll(".navbtn").forEach(b=>b.onclick=()=>{screen(b.dataset.screen);if(b.dataset.screen==="history")load()});

$("loginForm").onsubmit=async e=>{e.preventDefault();try{await signInWithEmailAndPassword(auth,$("loginEmail").value.trim(),$("loginPassword").value)}catch(err){msg("Email or password is incorrect.")}};
$("registerForm").onsubmit=async e=>{e.preventDefault();try{const name=$("registerName").value.trim(),email=$("registerEmail").value.trim();const c=await createUserWithEmailAndPassword(auth,email,$("registerPassword").value);await updateProfile(c.user,{displayName:name});await setDoc(doc(db,"users",c.user.uid),{displayName:name,email:email.toLowerCase(),createdAt:serverTimestamp(),settings:{weightUnit:"lb",theme:"dark"}})}catch(err){msg(err.code||"Could not create account.")}};
$("resetForm").onsubmit=async e=>{e.preventDefault();try{await sendPasswordResetEmail(auth,$("resetEmail").value.trim());msg("Password reset email sent. Check your inbox.",true)}catch(err){msg(err.code||"Could not send reset email.")}};
$("logoutBtn").onclick=()=>signOut(auth);

onAuthStateChanged(auth,async u=>{user=u;if(!u){$("appView").classList.add("hidden");$("authView").classList.remove("hidden");return}let name=u.displayName||"Athlete";try{const s=await getDoc(doc(db,"users",u.uid));if(s.exists()&&s.data().displayName)name=s.data().displayName}catch(e){}$("userName").textContent=name;$("profileName").textContent=name;$("userEmail").textContent=u.email||"";$("profileEmail").textContent=u.email||"";$("authView").classList.add("hidden");$("appView").classList.remove("hidden");screen("home");await load()});

function categories(){const g=$("categoryGrid");g.innerHTML="";Object.keys(EX).forEach(c=>{const b=document.createElement("button");b.className="category";b.innerHTML=`<strong>${c}</strong><span>${EX[c].length} exercises</span>`;b.onclick=()=>exercises(c);g.appendChild(b)})}
function exercises(c){$("categoryView").classList.add("hidden");$("exerciseView").classList.remove("hidden");$("activeView").classList.add("hidden");$("categoryTitle").textContent=c;const g=$("exerciseGrid");g.innerHTML="";EX[c].forEach(n=>{const b=document.createElement("button");b.className="exercise";b.innerHTML=`<strong>${n}</strong><span>${c}</span>`;b.onclick=()=>startEx(c,n);g.appendChild(b)})}
$("backBtn").onclick=()=>{$("exerciseView").classList.add("hidden");$("categoryView").classList.remove("hidden")};
$("startWorkoutBtn").onclick=()=>{screen("workout");$("categoryView").classList.remove("hidden");$("exerciseView").classList.add("hidden");$("activeView").classList.add("hidden")};

function startEx(c,n){if(!workout){workout={startedAt:new Date(),exercises:[]};startTimer()}active={category:c,name:n,sets:[{weight:"",reps:"8",done:false},{weight:"",reps:"8",done:false},{weight:"",reps:"8",done:false}]};$("exerciseView").classList.add("hidden");$("activeView").classList.remove("hidden");$("activeExerciseName").textContent=n;renderSets()}
function renderSets(){const list=$("setList");list.innerHTML="";active.sets.forEach((s,i)=>{const r=document.createElement("div");r.className="set-row";r.innerHTML=`<div class="set-num">${i+1}</div><input type="number" min="0" value="${s.weight}" placeholder="lb"><input type="number" min="0" value="${s.reps}" placeholder="reps"><button class="check ${s.done?"done":""}">${s.done?"✓":"○"}</button>`;const ins=r.querySelectorAll("input");ins[0].oninput=e=>s.weight=e.target.value;ins[1].oninput=e=>s.reps=e.target.value;r.querySelector(".check").onclick=()=>{s.done=!s.done;renderSets()};list.appendChild(r)})}
$("addSetBtn").onclick=()=>{const l=active.sets[active.sets.length-1];active.sets.push({weight:l?.weight||"",reps:l?.reps||"8",done:false});renderSets()};
$("addExerciseBtn").onclick=()=>{workout.exercises.push(active);active=null;$("activeView").classList.add("hidden");$("categoryView").classList.remove("hidden")};
$("finishWorkoutBtn").onclick=async()=>{if(active)workout.exercises.push(active);if(!workout.exercises.length)return;const end=new Date();try{await addDoc(collection(db,"users",user.uid,"workouts"),{startedAt:workout.startedAt,endedAt:end,createdAt:serverTimestamp(),durationSeconds:Math.max(1,Math.round((end-workout.startedAt)/1000)),exerciseCount:workout.exercises.length,exercises:workout.exercises.map(x=>({...x,sets:x.sets.map(s=>({weight:Number(s.weight||0),reps:Number(s.reps||0),done:!!s.done}))}))});workout=null;active=null;stopTimer();await load();screen("home");toast("Workout saved.","success")}catch(err){toast("Could not save workout.","error")}};

function startTimer(){stopTimer();timer=setInterval(()=>{if(!workout)return;const s=Math.floor((Date.now()-workout.startedAt)/1000);$("timer").textContent=`${String(Math.floor(s/60)).padStart(2,"0")}:${String(s%60).padStart(2,"0")}`},1000)}
function stopTimer(){if(timer)clearInterval(timer);timer=null}

async function load(){if(!user)return;try{const q=query(collection(db,"users",user.uid,"workouts"),orderBy("startedAt","desc"),limit(50));const s=await getDocs(q),ws=s.docs.map(d=>d.data());$("workoutCount").textContent=ws.length;$("streakCount").textContent=ws.length?1:0;renderList($("recentList"),ws.slice(0,5));renderList($("historyList"),ws)}catch(err){console.error(err)}}
function renderList(el,ws){el.innerHTML="";el.classList.remove("empty");if(!ws.length){el.classList.add("empty");el.textContent="No workouts saved yet.";return}ws.forEach(w=>{const d=w.startedAt?.toDate?w.startedAt.toDate():new Date();const c=document.createElement("div");c.className="workout-card";c.innerHTML=`<h4>${d.toLocaleDateString()} ${d.toLocaleTimeString([],{hour:"numeric",minute:"2-digit"})}</h4><div>${w.exerciseCount||w.exercises?.length||0} exercises • ${(w.exercises||[]).reduce((n,e)=>n+(e.sets?.length||0),0)} sets</div><p class="muted">${(w.exercises||[]).map(e=>e.name).join(", ")}</p>`;el.appendChild(c)})}
categories();
